[mcp_servers.filesystem]
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "C:/Users/Vincent/Documents/ELECTRON",
]
command = "npx"

[mcp_servers.memory]
args = [
    "-y",
    "@modelcontextprotocol/server-memory",
]
command = "npx"
