-- Migration: add folio and vendedor_nombre to movimientos_caja
-- Date: 2026-04-15
-- Context:
--   folio          → unique per-payment identifier (A-00001, A-00002, …)
--                    generated by registrarAbono at insert time
--   vendedor_nombre → display name of the staff member who registered the payment,
--                    denormalized for reporting without joining users tables

ALTER TABLE public.movimientos_caja
  ADD COLUMN IF NOT EXISTS folio          TEXT,
  ADD COLUMN IF NOT EXISTS vendedor_nombre TEXT;

COMMENT ON COLUMN public.movimientos_caja.folio IS
  'Human-readable unique folio per payment movement (e.g. A-00001). NULL for older rows.';
COMMENT ON COLUMN public.movimientos_caja.vendedor_nombre IS
  'Display name of the staff member who created this movement. NULL for older rows.';
